---
- hosts: localhost
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: https://github.com/Sanjana1455/perfectpet.git
        dest: /tmp/perfectpet

    - name: Build Docker Image
      shell: |
        cd /tmp/perfectpet
        docker build -t webapp-image .

    - name: Run Docker Container
      shell: docker run -d -p 80:8080 --name webapp-container webapp-image
